# docker-build-ci.yml - Docker 이미지 빌드용 CI 구성
# 이 파일은 data-validator 프로젝트에서만 사용합니다.

stages:
  - build
  - publish

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    # data-validator 프로젝트에서만 실행
    - if: '$CI_PROJECT_NAME != "data-validator"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - scripts/*.py
        - app/**/*.py
        - docker-build-ci.yml
        - Dockerfile
    - if: '$CI_COMMIT_TAG'
      when: always

publish_tagged_version:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    # data-validator 프로젝트에서만 실행
    - if: '$CI_PROJECT_NAME != "data-validator"'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: always
