# validation-ci.yml - 북마크 검증용 CI 구성
# 이 파일은 다른 프로젝트에서 include하여 사용합니다.

stages:
  - validate

validate_bookmarks:
  stage: validate
  image: registry.gitlab.com/sidebar-data/data-validator:latest
  script:
    - cd $CI_PROJECT_DIR
    - python3 /app/validate_bookmarks.py
  rules:
    # data-validator 프로젝트에서는 실행하지 않음
    - if: '$CI_PROJECT_NAME == "data-validator"'
      when: never
    # 머지 리퀘스트에서만 실행
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
